name: Create Backports for Android & LTS Kernels
on:
  workflow_dispatch:
    inputs:
      kernel_versions:
        description: 'Select LTS Kernel Versions (comma-separated)'
        required: true
        default: '6.6,6.1,5.15,5.10'
        type: string

jobs:
  create_tar:
    name: Build Backports
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64, arm, x86_64]
        kernel_version: [6.6, 6.1, 5.15, 5.10]  # LTS Kernels
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y coccinelle bc flex bison libssl-dev libelf-dev

      - name: Checkout Backports Repository
        uses: actions/checkout@v4
        with:
          path: backports

      - name: Set Up Cross-Compilation Toolchain
        run: |
          case "${{ matrix.arch }}" in
            arm64)
              sudo apt install -y gcc-aarch64-linux-gnu
              CROSS_COMPILE=aarch64-linux-gnu-
              ;;
            arm)
              sudo apt install -y gcc-arm-linux-gnueabihf
              CROSS_COMPILE=arm-linux-gnueabihf-
              ;;
            x86_64)
              CROSS_COMPILE=""
              ;;
          esac
          echo "CROSS_COMPILE=$CROSS_COMPILE" >> $GITHUB_ENV

      - name: Download LTS Kernel Source (v${{ matrix.kernel_version }})
        run: |
          git config --global user.name 'actions'
          git config --global user.email 'action@github.com'

          # Extract major version (first digit)
          KERNEL_MAJOR=$(echo "${{ matrix.kernel_version }}" | cut -d'.' -f1)

          # Download the kernel source
          wget -q https://cdn.kernel.org/pub/linux/kernel/v${KERNEL_MAJOR}.x/linux-${{ matrix.kernel_version }}.tar.xz
          tar xf linux-${{ matrix.kernel_version }}.tar.xz && rm -rf linux-${{ matrix.kernel_version }}.tar.xz

          mv linux-${{ matrix.kernel_version }} linux
          git -C linux init
          git -C linux add .
          git -C linux commit -sm "linux-${{ matrix.kernel_version }}"

      - name: Generate Backports Tarball
        working-directory: backports
        run: |
          ./gentree.py --refresh ${GITHUB_WORKSPACE}/linux ${GITHUB_WORKSPACE}/backports-${{ matrix.kernel_version }}

      - name: Check for Git Changes
        working-directory: backports
        run: |
          git diff

      - name: Build Backports for Android (v${{ matrix.kernel_version }})
        working-directory: backports
        run: |
          export ARCH=${{ matrix.arch }}
          export CROSS_COMPILE=$CROSS_COMPILE
          make defconfig
          make -j$(nproc)

      - name: Package Backports
        run: |
          tar -c backports-${{ matrix.kernel_version }}-${{ matrix.arch }} | xz > backports-${{ matrix.kernel_version }}-${{ matrix.arch }}.tar.xz
          sha256sum backports-${{ matrix.kernel_version }}-${{ matrix.arch }}.tar.xz > backports-${{ matrix.kernel_version }}-${{ matrix.arch }}.tar.xz.sha256

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backports-${{ matrix.kernel_version }}-${{ matrix.arch }}
          path: |
            backports-${{ matrix.kernel_version }}-${{ matrix.arch }}.tar.xz
            backports-${{ matrix.kernel_version }}-${{ matrix.arch }}.tar.xz.sha256

  release:
    needs: create_tar
    name: Release Backports
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Release Backports for LTS Kernels
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          prerelease: false
          name: "Backports for LTS Kernels"
          tag: "backports-lts"
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: artifacts/*
