name: Create backports CI

on:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: 'Select kernel v6.x version'
        required: true
        default: '6.14'
        type: string

jobs:
  create_tar:
    name: Create backports
    runs-on: ubuntu-24.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y coccinelle jq gnupg

      - name: Checkout backports
        uses: actions/checkout@v4
        with:
          path: backports

      - name: Download and verify kernel
        run: |
          wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${{ github.event.inputs.kernel_version }}.tar.xz
          wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${{ github.event.inputs.kernel_version }}.tar.sign
          gpg --keyserver keyserver.ubuntu.com --recv-keys 647F28654894E3BD457199BE38DBBDC86092693E
          gpg --verify linux-${{ github.event.inputs.kernel_version }}.tar.sign
          tar xf linux-${{ github.event.inputs.kernel_version }}.tar.xz
          mv linux-${{ github.event.inputs.kernel_version }} linux

      - name: Generate backports
        working-directory: backports
        run: |
          chmod +x gentree.py
          ./gentree.py --refresh  ${GITHUB_WORKSPACE}/linux ${GITHUB_WORKSPACE}/backports-${{ github.event.inputs.kernel_version }}

      - name: Check for git changes
        working-directory: backports
        run: |
          git diff || true

      - name: Pack backports
        run: |
          tar -cJf backports-${{ github.event.inputs.kernel_version }}.tar.xz backports-${{ github.event.inputs.kernel_version }}
          sha256sum backports-${{ github.event.inputs.kernel_version }}.tar.xz > backports-${{ github.event.inputs.kernel_version }}.sha256

      - name: Generate Changelog
        run: |
          git log --pretty=format:"%h - %s (%an, %ar)" -n 10 > changelog-${{ github.event.inputs.kernel_version }}.txt

      - name: Release build artifacts
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          prerelease: false
          name: backports v${{ github.event.inputs.kernel_version }}
          tag: v${{ github.event.inputs.kernel_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: |
            backports-${{ github.event.inputs.kernel_version }}.tar.xz
            backports-${{ github.event.inputs.kernel_version }}.tar.xz.sha256
            changelog-${{ github.event.inputs.kernel_version }}.txt
